apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
      version: v1
  template:
    metadata:
      labels:
        app: java
        version: v1
    spec:
      containers:
      - name: java
        image: "jakshaym/java-travel-app:latest"
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-v1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: java
    version: v1